require "pry"
require "httparty"
require "json"

require_relative "./modules/star_wars_module"
require_relative "./modules/get_film"
require_relative "./modules/get_vehicles_and_starships"
require_relative "./modules/get_characters"
require_relative "./modules/get_species"
require_relative "./star_wars_cli/cli"
require_relative "./star_wars_cli/api"
require_relative "./star_wars_cli/person"
require_relative "./star_wars_cli/star_wars_controller"
require_relative "./star_wars_cli/species"
require_relative "./star_wars_cli/planets"
require_relative "./star_wars_cli/starship"
require_relative "./star_wars_cli/vehicle"
require_relative "./star_wars_cli/film"