require "pry"
require "httparty"
require "json"

require_relative "./star_wars_cli/cli"
require_relative "./star_wars_cli/api"
require_relative "./star_wars_cli/person"
require_relative "./star_wars_cli/star_wars_controller"
require_relative "./star_wars_cli/species"
require_relative "./star_wars_cli/planets"
require_relative "./star_wars_cli/starship"
require_relative "./star_wars_cli/vehicle"